application: reboot11
version: 1
runtime: python
api_version: 1

handlers:
- url: /schedule(\.json)?
  script: schedule.py

- url: /schedule/import
  script: schedule.py
  login: admin

- url: /activity.*
  script: activity.py

- url: .*
  script: main.py
